#Env vars

#Packages List

DEV_TOOLS=(
neovim
tmux
bat
go
deno
lua
luarocks
nvm
tig
zsh
)

SYSTEM_UTILS=(
hyprlock
hyprshot
waybar
gnome-keyring
libsecret
ripgrep
pkgfile
btop
jq
curl
ghostty
fd
flatpak
man-pages
man-db
fzf
stow
rofi
tree-sitter-cli
)

STUFF=(
discord
steam
)

FONTS=(
ttf-jetbrains-mono-nerd
noto-fonts-cjk
)

YAY_STUFF=(
oh-my-posh-bin
brave-bin
balena-etcher
)

STOW=(
zshrc
nvim
ohmyposh 
tmux
ghostty 
bat
)
